#!/usr/bin/env python3
"""
Generate docker-compose.generated.yml with N n8n services for multi-tenant self-host.

Reads from environment:
  N8N_COUNT         Number of n8n instances (default: 25)
  BASE_HOST         Base domain for subdomains, e.g. yourdomain.com or IP.nip.io
  USE_LETSENCRYPT   If set (e.g. true), add tls.certresolver=letsencrypt. Otherwise use Traefik default cert (no 404 when LE fails)

Output: docker-compose.generated.yml in the project root (parent of scripts/).

Usage:
  N8N_COUNT=20 BASE_HOST=yourdomain.com python scripts/generate-compose.py
  # Or on Windows (PowerShell):
  $env:N8N_COUNT=20; $env:BASE_HOST="yourdomain.com"; python scripts/generate-compose.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path


def env_int(key: str, default: int) -> int:
    raw = os.environ.get(key)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def env_str(key: str, default: str) -> str:
    return os.environ.get(key, default)


def env_bool(key: str, default: bool = False) -> bool:
    raw = os.environ.get(key, "").strip().lower()
    return raw in ("1", "true", "yes") if raw else default


def main() -> int:
    n8n_count = env_int("N8N_COUNT", 25)
    base_host = env_str("BASE_HOST", "yourdomain.com").strip().rstrip("/")
    use_letsencrypt = env_bool("USE_LETSENCRYPT", False)

    if n8n_count < 1 or n8n_count > 99:
        print("N8N_COUNT must be between 1 and 99.", file=sys.stderr)
        return 1

    # Output next to repo root (parent of scripts/)
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    out_path = repo_root / "docker-compose.generated.yml"

    lines = [
        "# Generated by scripts/generate-compose.py - do not edit by hand.",
        f"# N8N_COUNT={n8n_count} BASE_HOST={base_host}",
        "# Uses named volumes for n8n data (no chown needed on new machines).",
        "",
        "services:",
    ]
    volume_names = []

    for i in range(1, n8n_count + 1):
        subdomain = f"n8n{i:02d}"  # n8n01, n8n02, ... n8n20
        host = f"{subdomain}.{base_host}"
        webhook_url = f"https://{host}/"
        service_name = f"n8n-{i}"
        db_name = f"n8n_{i}"
        volume_name = f"n8n_{i}_data"
        volume_names.append(volume_name)

        # Traefik rule: Host(`n8n01.yourdomain.com`) — quoted in YAML for backticks
        traefik_rule_value = f'Host(`{host}`)'
        # When USE_LETSENCRYPT is not set: add router on "web" (HTTP) so site works without cert; optional router on websecure with LE
        tls_label = f'"traefik.http.routers.{service_name}.tls.certresolver=letsencrypt"' if use_letsencrypt else None
        # Router on web (HTTP) so that when LE fails or no cert, users can still use http://host
        http_router = f'"traefik.http.routers.{service_name}-web.rule={traefik_rule_value}"'
        http_entry = f'"traefik.http.routers.{service_name}-web.entrypoints=web"'
        http_svc = f'"traefik.http.routers.{service_name}-web.service={service_name}"'
        # เมื่อเข้าแบบ HTTP (ไม่มี LE) ต้องปิด secure cookie เพื่อให้ login ได้
        secure_cookie_line = "      - N8N_SECURE_COOKIE=false\n" if not use_letsencrypt else ""

        block = f"""
  {service_name}:
    image: docker.n8n.io/n8nio/n8n
    container_name: {service_name}
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE={db_name}
      - DB_POSTGRESDB_USER=${{POSTGRES_USER:-n8n}}
      - DB_POSTGRESDB_PASSWORD=${{POSTGRES_PASSWORD:-n8npassword}}
      - GENERIC_TIMEZONE=${{GENERIC_TIMEZONE:-Asia/Bangkok}}
      - WEBHOOK_URL={webhook_url}
      - N8N_HOST={host}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
{secure_cookie_line}
    volumes:
      - {volume_name}:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=n8n_web
      - "traefik.http.routers.{service_name}.rule={traefik_rule_value}"
      - traefik.http.routers.{service_name}.entrypoints=websecure
      - traefik.http.routers.{service_name}.service={service_name}
      - {http_router}
      - {http_entry}
      - {http_svc}
"""
        if tls_label:
            block += f"      - {tls_label}\n"
        block += f"""      - traefik.http.services.{service_name}.loadbalancer.server.port=5678
"""
        lines.append(block)

    # Declare named volumes so Docker creates them with correct ownership for container user
    lines.append("\nvolumes:")
    for v in volume_names:
        lines.append(f"  {v}:")

    content = "\n".join(lines).lstrip()
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {n8n_count} n8n services to {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
